export type EmojiEntry = { name: string; char: string; keywords?: string[] };

export const EMOJI: EmojiEntry[] = [
    { name: 'smile', char: '😄', keywords: ['happy', 'joy'] },
    { name: 'grin', char: '😁', keywords: ['happy'] },
    { name: 'joy', char: '😂', keywords: ['lol', 'laugh'] },
    { name: 'heart_eyes', char: '😍', keywords: ['love'] },
    { name: 'wink', char: '😉' },
    { name: 'blush', char: '😊' },
    { name: 'sunglasses', char: '😎', keywords: ['cool'] },
    { name: 'thinking', char: '🤔', keywords: ['think'] },
    { name: 'sweat_smile', char: '😅' },
    { name: 'rofl', char: '🤣' },
    { name: 'cry', char: '😢' },
    { name: 'sob', char: '😭' },
    { name: 'angry', char: '😠' },
    { name: 'rage', char: '😡' },
    { name: 'eyes', char: '👀' },
    { name: 'zzz', char: '😴', keywords: ['sleep'] },
    { name: 'wave', char: '👋', keywords: ['hello', 'hi'] },
    { name: 'thumbsup', char: '👍', keywords: ['+1', 'yes'] },
    { name: 'thumbsdown', char: '👎', keywords: ['-1', 'no'] },
    { name: 'ok_hand', char: '👌' },
    { name: 'clap', char: '👏' },
    { name: 'pray', char: '🙏', keywords: ['thanks', 'please'] },
    { name: 'muscle', char: '💪' },
    { name: 'point_right', char: '👉' },
    { name: 'point_left', char: '👈' },
    { name: 'raised_hands', char: '🙌' },
    { name: 'handshake', char: '🤝' },
    { name: 'heart', char: '❤️', keywords: ['love'] },
    { name: 'broken_heart', char: '💔' },
    { name: 'fire', char: '🔥', keywords: ['hot', 'lit'] },
    { name: 'sparkles', char: '✨' },
    { name: 'star', char: '⭐' },
    { name: 'boom', char: '💥', keywords: ['explode'] },
    { name: 'rocket', char: '🚀', keywords: ['ship', 'launch'] },
    { name: 'tada', char: '🎉', keywords: ['party', 'celebrate'] },
    { name: 'confetti', char: '🎊' },
    { name: 'trophy', char: '🏆', keywords: ['win'] },
    { name: 'medal', char: '🏅' },
    { name: 'gift', char: '🎁' },
    { name: 'hundred', char: '💯', keywords: ['100'] },
    { name: 'check', char: '✅', keywords: ['done', 'yes'] },
    { name: 'x', char: '❌', keywords: ['no', 'cancel'] },
    { name: 'warning', char: '⚠️', keywords: ['caution'] },
    { name: 'question', char: '❓' },
    { name: 'exclamation', char: '❗' },
    { name: 'bulb', char: '💡', keywords: ['idea'] },
    { name: 'bookmark', char: '🔖' },
    { name: 'pencil', char: '✏️', keywords: ['write', 'edit'] },
    { name: 'memo', char: '📝', keywords: ['note'] },
    { name: 'book', char: '📖' },
    { name: 'books', char: '📚' },
    { name: 'clipboard', char: '📋' },
    { name: 'calendar', char: '📅', keywords: ['date'] },
    { name: 'alarm', char: '⏰', keywords: ['clock'] },
    { name: 'stopwatch', char: '⏱️', keywords: ['timer'] },
    { name: 'hourglass', char: '⏳' },
    { name: 'mag', char: '🔍', keywords: ['search', 'find'] },
    { name: 'lock', char: '🔒' },
    { name: 'unlock', char: '🔓' },
    { name: 'key', char: '🔑' },
    { name: 'link', char: '🔗' },
    { name: 'computer', char: '💻' },
    { name: 'phone', char: '📱' },
    { name: 'floppy', char: '💾', keywords: ['save'] },
    { name: 'gear', char: '⚙️', keywords: ['settings'] },
    { name: 'hammer', char: '🔨', keywords: ['fix', 'build'] },
    { name: 'wrench', char: '🔧', keywords: ['fix', 'tool'] },
    { name: 'bug', char: '🐛' },
    { name: 'bell', char: '🔔' },
    { name: 'tag', char: '🏷️', keywords: ['label'] },
    { name: 'pin', char: '📌' },
    { name: 'up', char: '⬆️' },
    { name: 'down', char: '⬇️' },
    { name: 'left', char: '⬅️' },
    { name: 'right', char: '➡️' },
    { name: 'arrow_up', char: '↑' },
    { name: 'arrow_down', char: '↓' },
    { name: 'coffee', char: '☕' },
    { name: 'pizza', char: '🍕' },
    { name: 'beer', char: '🍺' },
    { name: 'cake', char: '🍰' },
    { name: 'sun', char: '☀️' },
    { name: 'moon', char: '🌙' },
    { name: 'cloud', char: '☁️' },
    { name: 'rain', char: '🌧️' },
    { name: 'snow', char: '❄️' },
    { name: 'earth', char: '🌍', keywords: ['world', 'globe'] },
    { name: 'dog', char: '🐶' },
    { name: 'cat', char: '🐱' },
    { name: 'rainbow', char: '🌈' },
    { name: 'brain', char: '🧠' },
    { name: 'eye', char: '👁️' },
    { name: 'ghost', char: '👻' },
    { name: 'robot', char: '🤖' },
    { name: 'alien', char: '👽' },
    { name: 'skull', char: '💀' },
    { name: 'zap', char: '⚡' },
    { name: 'snowflake', char: '❄️' },
    { name: 'music', char: '🎵' },
    { name: 'camera', char: '📷' },
    { name: 'microphone', char: '🎤' },
    { name: 'headphones', char: '🎧' },
];
